### PR TITLE
chore: size based retention policy to test

### PR DESCRIPTION
**Pull request by ABresting**
Description:
This PR is to put the newly added size-based retention policy in the Waku node to test.

### CODE REVIEW

**Review by alrevuelta — COMMENTED** [review]
Haven't followed this feature, so maybe I'm missing context, but imho its better to keep x days than x GB. From a protocol usability perspective I think we should "guarantee" eg 30 days rather than x GB.

RLN v2 should make bandwidth more predictable (see [ref](https://github.com/waku-org/research/issues/22)) and if bandwidth is more predictable/capped, then the amout of GB per month would also be kind of under control. So it should be safer to specify the retention time in days (once we reach RLN v2).

Regarding the PR, I'm not sure on its impact in status, so would like to wait for @jm-clius input.

**Comment by apentori** [comment]
@alrevuelta  the `wakuv2.prod` and `wakuv2.test` often have disk space issue cf : https://github.com/status-im/infra-nim-waku/issues/86.

From what i understand those fleet (event the `prod` one) are used only for test.

@ABresting is it possible to combine the time and size retention policy ?

**Comment by jakubgs** [comment]
>Haven't followed this feature, so maybe I'm missing context, but imho its better to keep x days than x GB. From a protocol usability perspective I think we should "guarantee" eg 30 days rather than x GB.

That makes sense for a fleet that is actually being used by the app. This one isn't. This repo defined development/research fleets for the Waku team, and it makes more sense to limit by size to lower the maintenance cost. Unless there's a good reason from developers to keep it at 30 days.

**Review by jakubgs — APPROVED** [review]

**Comment by ABresting** [comment]
> @alrevuelta the `wakuv2.prod` and `wakuv2.test` often have disk space issue cf : #86.
> 
> From what i understand those fleet (event the `prod` one) are used only for test.
> 
> @ABresting is it possible to combine the time and size retention policy ?

Very interesting point, so far, isn't possible with the current codebase. But will like to hear the thoughts of @jm-clius and @Ivansete-status.

**Pull request merged**
