### PR TITLE
feat: enable dns discovery in wakuv2.test

### PR DESCRIPTION
**Pull request by jm-clius**
This PR does two related things:
1. Updates the existing DNS entries for the `wakuv2` fleets (both `prod` and `test`) to the latest ENR records. The ENR records now contain UDP connection information for Discovery v5 as well.
2. Enables and configures DNS discovery on the `wakuv2.test` fleet only. NB: this requires changes in the role to be merged first. Open PR here: https://github.com/status-im/infra-role-nim-waku/pull/4

### Why will this be helpful?

- Once the fleet nodes use DNS discovery to connect to each other, we can remove the `Peer` table and deprecate peer persistence plus the silly reconnection logic we needed to maintain a stable connection between fleet nodes.
- The discv5 routing table will be properly initialised in each fleet node, allowing them to be useful as discv5 bootstrap nodes in other peers joining the network. cc @kaiserd

### CODE REVIEW

**Comment by kaiserd** [comment]
nice :+1:

**Review by jakubgs — APPROVED** [review]
LGTM, but could we maybe split this into two commits? Since the `group_vars` change depends on the Terraform changes to the DNS records.

**Comment by jm-clius** [comment]
> LGTM, but could we maybe split this into two commits? Since the `group_vars` change depends on the Terraform changes to the DNS records.

Done: updated this PR to only include the config changes. DNS entries updated in: https://github.com/status-im/infra-nim-waku/pull/55

**Comment by jakubgs** [comment]
You misunderstood me. I said split it into two commits, not two PRs. But it is what it is, and I approved #55.

**Comment by jm-clius** [comment]
Hahaha. Yes, I didn't even misunderstand - I simply didn't read properly :D. #55 has been merged and this PR has been rebased.

**Comment by jakubgs** [comment]
DNS entries created:
```
 > dig +short TXT test.waku.nodes.status.im
"enrtree-root:v1 e=6MRD3IKZEE5COX7TYBUZC5L4MU l=FDXN3SN67NA5DKA4J2GOK7BVQI seq=1 sig=bYCHTQ7V7QQbfhgS9rQKgroExOlq9re5WjGV_3YrAF8NnWCRPy9IXtulvlEtijXkk8sw9yEGPFDKEYzkeCLWUAA"
```
And node changes deployed to `wakuv2.test`:
```
 > a wakuv2.test -a 'grep dns-discovery /docker/nim-waku-v2/docker-compose.yml'
node-01.do-ams3.wakuv2.test | CHANGED | rc=0 >>
      --dns-discovery=true
      --dns-discovery-url=enrtree://AOFTICU2XWDULNLZGRMQS4RIZPAZEHYMV4FYHAPW563HNRAOERP7C@test.waku.nodes.status.im
node-01.gc-us-central1-a.wakuv2.test | CHANGED | rc=0 >>
      --dns-discovery=true
      --dns-discovery-url=enrtree://AOFTICU2XWDULNLZGRMQS4RIZPAZEHYMV4FYHAPW563HNRAOERP7C@test.waku.nodes.status.im
node-01.ac-cn-hongkong-c.wakuv2.test | CHANGED | rc=0 >>
      --dns-discovery=true
      --dns-discovery-url=enrtree://AOFTICU2XWDULNLZGRMQS4RIZPAZEHYMV4FYHAPW563HNRAOERP7C@test.waku.nodes.status.im
```

**Comment by jakubgs** [comment]
But something is not right:
```
ERR 2022-07-22 11:23:12.720+00:00 Failed to resolve DNS record               topics="dnsdisc.client" tid=1 file=client.nim:74 domain=EGF7DJ6CEODMEBFE2UF7XQOAAI
/app/waku/v2/node/wakunode2.nim(1418) wakunode2
/app/waku/v2/node/wakunode2.nim(1310) startNode
/app/vendor/nim-chronos/chronos/asyncloop.nim(1074) waitFor
/app/vendor/nim-chronos/chronos/asyncloop.nim(279) poll
/app/vendor/nim-chronos/chronos/asyncfutures2.nim(365) futureContinue
/app/vendor/nim-libp2p/libp2p/nameresolving/dnsresolver.nim(86) getDnsResponse
/app/vendor/nimbus-build-system/vendor/Nim/lib/system/assertions.nim(22) raiseAssert
/app/vendor/nimbus-build-system/vendor/Nim/lib/system/fatal.nim(49) sysFatal
[[reraised from:
/app/waku/v2/node/wakunode2.nim(1418) wakunode2
/app/waku/v2/node/wakunode2.nim(1310) startNode
/app/vendor/nim-chronos/chronos/asyncloop.nim(1074) waitFor
/app/vendor/nim-chronos/chronos/asyncloop.nim(279) poll
/app/vendor/nim-chronos/chronos/asyncfutures2.nim(365) futureContinue
/app/vendor/nim-libp2p/libp2p/nameresolving/dnsresolver.nim(88) getDnsResponse
]]
[[reraised from:
/app/waku/v2/node/wakunode2.nim(1418) wakunode2
/app/waku/v2/node/wakunode2.nim(1310) startNode
/app/vendor/nim-chronos/chronos/asyncloop.nim(1074) waitFor
/app/vendor/nim-chronos/chronos/asyncloop.nim(279) poll
/app/vendor/nim-chronos/chronos/asyncfutures2.nim(387) futureContinue
]]
Error: unhandled exception: /app/vendor/dnsclient.nim/src/dnsclientpkg/protocol.nim(164, 10) `data.atEnd()`  [AssertionError]
```

**Comment by jakubgs** [comment]
The referenced DNS record clearly exists:
```
 > dig +short TXT EGF7DJ6CEODMEBFE2UF7XQOAAI.test.waku.nodes.status.im 
"enr:-Nm4QC0_ClHzbsutYzgT3jJm7ZY1D4shylAdd6Ac-L4uwAUha1oHM0zwoEkTORVt94W5Cpa0IiyrTcXAYLgpRXpVNUsBgmlkgnY0gmlwhC_y0kmKbXVsdGlhZGRyc7g6ADg2MW5vZGUtMDEuYWMtY24taG9uZ2tvbmctYy53YWt1djIudGVzdC5zdGF0dXNpbS5uZXQGH0DeA4lzZWNwMjU2azGhAhAm-P4q6mWONKcGnbLPU8WXZJ4Qs3A" "xIbrycvc7PVKsg3RjcIJ2X4N1ZHCCIyiFd2FrdTIP"
```

**Comment by jakubgs** [comment]
Looks like deploying the newest `master` fixed it: https://ci.status.im/job/nim-waku/job/deploy-v2-test/348/

**Pull request merged**
