### PR TITLE
Revert "wakuv2-shards: init new fleet for static sharding"

### PR DESCRIPTION
**Pull request by yakimant**
This reverts commit e38881b66c9276801b04fc6ef442be514a3345c3.

### CODE REVIEW

**Comment by yakimant** [comment]
Cleanup done:
- cloud infra
- terraform state, workspace
- consul nodes

**Review by jakubgs — COMMENTED** [review]
Just reverting is not enough. You also need to remove the entries in the inventory.

But if you do that then it's not just a revert. So don't call it a revert.

**Review by jakubgs — APPROVED** [review]
Squash this into one commit with a title like: `wakuv2-shards: decommission fleet`

**Comment by yakimant** [comment]
Removed CI job

**Pull request merged**
